language: node_js
sudo: required
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- stable
os:
- linux
addons:
  chrome: stable
services:
- docker
before_install:
# set up a docker image with emscripten ready to go
- docker run -dit --name emscripten -v $(pwd):/project trzeci/emscripten:latest bash
script:
# install the library dependencies
- ./ci-install.sh
# run the build script on the docker image
- docker exec -it emscripten bash -c 'cd /project; ./build.sh'
# run tests locally
- npm run test
- commitlint-travis
after_success:
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
